Class <- c(rep("character",2),rep("numeric",7))
Sample<- read.table("household_power_consumption.txt",header=TRUE,sep=";",na.strings = "?",colClasses=Class)
Data <- subset(Sample,Date == "1/2/2007" |  Date == "2/2/2007" )
Data$Time <- strptime(paste(Data$Date,Data$Time),"%d/%m/%Y%H:%M:%S")
Data$Date = as.Date(Data$Date,format="%d/%m/%Y")
range <- range(0.000,Data$Sub_metering_1,Data$Sub_metering_2,Data$Sub_metering_3)
png('plot3.png')
par(mar=c(2.4,5.1,2.1,2.1))
plot(Data$Time,type="l",Data$Sub_metering_1,ylim=range,ylab="Energy sub metering")
lines(Data$Time,Data$Sub_metering_2,type="l",col="red")
lines(Data$Time,Data$Sub_metering_3,type="l",col="purple")
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=c(1,1),col=c("black","red","purple"))
dev.off()