Class <- c(rep("character",2),rep("numeric",7))
Sample<- read.table("household_power_consumption.txt",header=TRUE,sep=";",na.strings = "?",colClasses=Class)
Data <- subset(Sample,Date == "1/2/2007" |  Date == "2/2/2007" )
Data$Time <- strptime(paste(Data$Date,Data$Time),"%d/%m/%Y%H:%M:%S")
Data$Date = as.Date(Data$Date,format="%d/%m/%Y")
par(mar=c(2.4,5.1,2.1,2.1))
plot(Data$Time, Data$Global_active_power,type="n",ylab="Global Active Power (kilowatts)")
lines(Data$Time,Data$Global_active_power)
dev.copy(png,"plot2.png",width = 480, height = 480)
dev.off()